### ISSUE TITLE
Initial server render does not embed styles

### ISSUE THREAD

**Issue by empz** [xabikos/aspnetcore-react-redux-template#3]
The TypeScript version of the template seems to apply styles just fine on the initial server rendering (or if javascript is disabled).

This version needs javascript to apply the styles and sometimes when you do a full page refresh you can see the page without styles. Same thing if javascript is disabled.

![image](https://cloud.githubusercontent.com/assets/412489/16111031/29dc7118-3387-11e6-9493-8d2954863bde.png)

**Comment by xabikos** [comment]
What you described happens only for development environment in which I don't consider disable the JavaScript a realistic scenario. The reason that this is happen is because in this version the styles are embedded in a style tag inside the header of the page. I find this approach easier to implement with live reload in mind. Normally this is quite fast and I am not quite sure why there is this small time when the page looks like the screen you provide on server side rendering. I am going to look into it.

**Comment by empz** [comment]
If it only happens in development environment that's ok. I was just wondering why the difference with the TypeScript version. Isn't the styles loading the same in both?

**Comment by xabikos** [comment]
Yes this only happens in development mode. And there is a difference with TypeScript version. In this version all the styles are embedded inside styles tags inside the head of the page on development environment. In TypeScript version the styles are a usual external css file.
